# version: '3'
# services:
#   db:
#     build:
#       context: .
#       dockerfile: ./docker/mysql/Dockerfile
#     ports:
#       - '3306:3306'
#     volumes:
#       - db_data:/var/lib/mysql
#     extends:
#       file: ./docker/mysql/password.yml
#       service: password
#     environment:
#       MYSQL_ROOT_PASSWORD: password
#       MYSQL_USER: root
#       MYSQL_PASSWORD: password
#       TZ: "Asia/Tokyo"
#       SECRET_KEY_BASE: cda17ab72c590d3af03b656e8903e3ea55814d6ac67c67c8641840aa9cf8b8087b1a54a42760082a5510aebda67875e9ce712aa8d93a5fb2137b60b583ad8afb
#     command: --default-authentication-plugin=mysql_native_password

#   app:
#     build:
#       context: .
#       dockerfile: ./docker/rails/Dockerfile
#     # command: >
#     #   bash -c "bundle exec rails assets:precompile &&
#     #   bundle exec rails db:migrate &&
#     #   bundle exec unicorn -p 3000 -c /app/config/unicorn.rb"
#     command: bundle exec unicorn -p 3000 -c /app/config/unicorn.rb
#     # command: bundle exec rails s -p 3000 -b '0.0.0.0'
#     ports:
#       - '3000:3000'
#     volumes:
#       - /var/tmp
#       - .:/app
#     depends_on:
#       - db
#     environment:  # 必要な環境変数を直接指定
#       MYSQL_ROOT_PASSWORD: password
#       MYSQL_USER: root
#       MYSQL_PASSWORD: password
#       TZ: "Asia/Tokyo"  # 必要な場合はタイムゾーンを指定

#   nginx:
#     build:
#       context: .
#       dockerfile: ./docker/nginx/Dockerfile
#     ports:
#       - '80:80'
#     volumes_from:
#       - app
      
# volumes:
#   db_data:




version: '3'

services:
  rails:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
    command: ["bundle", "exec", "unicorn", "-p", "3000", "-c", "/app/config/unicorn.rb"]

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - rails
